version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
      open-pull-requests-limit: 10
      versioning-strategy: increase-if-necessary
    - package-ecosystem: npm
      directory: '/examples/simple-app'
      schedule:
          interval: weekly
      open-pull-requests-limit: 10
      versioning-strategy: increase-if-necessary
