yarnPath: '.yarn/releases/yarn-berry.cjs'
packageExtensions:
    '@dhis2/cli-utils@*':
        dependencies:
            glob: '*'
            '@semantic-release/error': '*'
            'aggregate-error': '*'
