yarnPath: .yarn/releases/yarn-2.4.0.cjs
packageExtensions:
    '@dhis2/cli-utils@*':
        dependencies:
            '@semantic-release/error': '*'
            aggregate-error: '*'
            glob: '*'
