[build]
  publish = "dist"

  # Default build command.
  command = "yarn docs:build"
  ignore = "echo $CACHED_COMMIT_REF && echo $COMMIT_REF && git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs/ CHANGELOG.md package.json"
