name: 'dhis2: verify (lib)'

on: push

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    NPM_TOKEN: ${{secrets.DHIS2_BOT_NPM_TOKEN}}
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    CI: true

jobs:
    install:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: |
                      .yarn/**
                      **/node_modules
                      .pnp.js
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Install
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install --immutable

    build:
        runs-on: ubuntu-latest
        needs: install
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: |
                      .yarn/**
                      **/node_modules
                      .pnp.js
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Build
              run: yarn build

            - uses: actions/upload-artifact@v2
              with:
                  name: lib-build
                  path: |
                      **/build
                      cli/assets
                      !**/node_modules
                  retention-days: 1

    lint:
        runs-on: ubuntu-latest
        needs: [install, build]
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: |
                      .yarn/**
                      **/node_modules
                      .pnp.js
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            
            - uses: actions/download-artifact@v2
              with:
                  name: lib-build
            
            - name: Generate i18n
              run: yarn i18n:generate

            - name: Lint
              run: yarn lint

    test:
        runs-on: ubuntu-latest
        needs: [install, build]
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: |
                      .yarn/**
                      **/node_modules
                      .pnp.js
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - uses: actions/download-artifact@v2
              with:
                  name: lib-build

            - name: Generate i18n
              run: yarn i18n:generate

            - name: Test
              run: yarn test

    build-example:
        runs-on: ubuntu-latest
        needs: [install, build]
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: |
                      .yarn/**
                      **/node_modules
                      .pnp.js
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - uses: actions/download-artifact@v2
              with:
                  name: lib-build

            - name: Build example
              run: yarn build:example

    publish:
        runs-on: ubuntu-latest
        needs: [build, lint, test, build-example]
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/download-artifact@v2
              with:
                  name: lib-build

            - name: Publish to NPM
              run: yarn dlx --package @dhis2/cli-utils d2-utils release --publish npm
