name: 'dhis2: auto-merge (dependabot)'

on:
    check_suite:
        types:
            - completed
    pull_request:
        types:
            - edited
            - labeled
            - opened
            - ready_for_review
            - reopened
            - synchronize
            - unlabeled
            - unlocked

jobs:
    merge-me:
        runs-on: ubuntu-latest
        steps:
            - name: Merge me!
              uses: ridedott/merge-me-action@master
              with:
                  # This must be used as GitHub Actions token does not support
                  # pushing to protected branches.
                  GITHUB_LOGIN: dependabot
                  GITHUB_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
                  MERGE_METHOD: SQUASH
